config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :conversations do    
    resources :messages 
  end 

  root to: "main#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_messageable 

  def name 
    "User #{id}"
  end 

  def mailboxer_email(object)
    nil
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController 
  before_action :get_mailbox 
  def index  
    @conversations = @mailbox.inbox.paginate(page: params[:page], per_page: 10)

       
  end 

  private 

  def get_mailbox 
    @mailbox ||= current_user.mailbox
  end 
end 

app/controllers/main_controller.rb
class MainController < ApplicationController 
  
  def index 
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.erb
<h1>Conversations</h1>

<% @conversations.each do |conversation| %>
  <div>
    <%= link_to conversation.subject, conversation_path(conversation) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messaging</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>